version: 2
updates:
  # Primary: keep Python dependencies up-to-date
  - package-ecosystem: "pip"
    directory: "/"                      # location of requirements.txt / pyproject.toml
    schedule:
      interval: "weekly"                # regular cadence for non-security updates
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"             # try to keep PRs up-to-date automatically
    allow:
      - dependency-type: "direct"       # focus on direct deps by default
    separate-security-updates: true     # open security fixes as separate, high-priority PRs
    labels:
      - "dependencies"
      - "dependabot"
      - "automerge"
    assignees:
      - "Ethanjoyce2010"
    reviewers:
      - "Ethanjoyce2010"
    commit-message:
      prefix: "chore(deps)"

  # Keep GitHub Actions used in CI up-to-date (common source of transitive security fixes)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    separate-security-updates: true
    labels:
      - "ci"
      - "dependencies"
      - "dependabot"
